# Generated by Django 5.0.6 on 2024-06-20 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_configuration', '0002_condition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condition',
            old_name='ebay_condition',
            new_name='ebay_condition_id',
        ),
    ]
