# Generated by Django 5.0.6 on 2024-06-20 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_configuration', '0003_rename_ebay_condition_condition_ebay_condition_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FilterCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_configuration.category')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_configuration.filter')),
            ],
            options={
                'unique_together': {('filter', 'category')},
            },
        ),
    ]
