# Generated by Django 5.0.6 on 2024-06-21 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_configuration', '0004_filter_filtercategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtercategory',
            name='download_status',
            field=models.BooleanField(default=False),
        ),
    ]
