# Generated by Django 5.0.6 on 2024-06-21 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_configuration', '0005_filtercategory_download_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filtercategory',
            old_name='download_status',
            new_name='status',
        ),
    ]
