# Generated by Django 5.0.6 on 2024-06-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_configuration', '0006_rename_download_status_filtercategory_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=30, unique=True)),
                ('country', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
