# Generated by Django 5.0.6 on 2024-06-28 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_configuration', '0007_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_configuration.category')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_configuration.condition')),
            ],
            options={
                'unique_together': {('condition', 'category')},
            },
        ),
    ]
