# Generated by Django 5.0.6 on 2024-07-02 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_configuration', '0008_conditioncategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodelcategory',
            name='brand_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product_configuration.brandcategory'),
            preserve_default=False,
        ),
    ]
