# Generated by Django 5.0.6 on 2024-07-02 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_configuration', '0009_productmodelcategory_brand_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodelcategory',
            name='brand_category',
        ),
    ]
