# Generated by Django 5.0.7 on 2024-07-24 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product_configuration.category')),
            ],
        ),
        migrations.CreateModel(
            name='MobileScrapingProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_model', models.CharField(blank=True, default='', max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_configuration.condition')),
                ('scraping_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping_scheduler.scrapingprocess')),
            ],
            options={
                'unique_together': {('scraping_process', 'condition')},
            },
        ),
    ]
