# Generated by Django 5.0.7 on 2024-07-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_configuration', '0001_initial'),
        ('scraping_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mobilescrapingprocess',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='mobilescrapingprocess',
            name='is_sold_listing',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='mobilescrapingprocess',
            unique_together={('scraping_process', 'condition', 'is_sold_listing')},
        ),
    ]
