# Generated by Django 5.0.7 on 2024-09-05 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitor_analysis', '0002_storecategory'),
        ('scraping_scheduler', '0003_specificproductprocess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EbayStoreProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ebay_store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='competitor_analysis.ebaystore')),
            ],
        ),
    ]
