from .users_serializers import CustomUserSerializer, CustomRegisterSerializer
from .roles_serializers import RoleSerializer, RoleCreateSerializer
from .permissions_serializers import PermissionSerializer, ModulePermissionSerializer , ModuleWithPermissionSerializer
from .modules_serializers import ModuleSerializer 
from .token_serializers import CustomTokenObtainPairSerializer