# Generated by Django 5.0.6 on 2024-07-11 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_configuration', '0012_remove_productmodelcategory_brand_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobhilePhones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sold_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ebay_item_id', models.IntegerField()),
                ('product_url', models.TextField()),
                ('image', models.TextField()),
                ('sold_date', models.DateField()),
                ('created_ad', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_configuration.brandcategory')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_configuration.category')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_configuration.colorcategory')),
                ('condition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_configuration.condition')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_configuration.location')),
                ('lock_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_configuration.lockstatus')),
                ('product_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_configuration.productmodelcategory')),
                ('storage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_configuration.storage')),
            ],
            options={
                'unique_together': {('title', 'sold_date', 'product_url')},
            },
        ),
    ]
