# Generated by Django 5.0.6 on 2024-07-11 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_products', '0001_initial'),
        ('product_configuration', '0012_remove_productmodelcategory_brand_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MobhilePhones',
            new_name='MobilePhones',
        ),
    ]
