# Generated by Django 5.0.7 on 2024-07-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_products', '0002_rename_created_ad_mobilephone_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilephone',
            name='ebay_item_id',
            field=models.BigIntegerField(),
        ),
    ]
