# Generated by Django 5.0.7 on 2024-07-30 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_products', '0001_initial'),
        ('product_configuration', '0002_alter_conditioncategory_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveMobilePhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('ebay_item_id', models.BigIntegerField()),
                ('product_url', models.CharField(max_length=255, unique=True)),
                ('image', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_configuration.brandcategory')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_configuration.category')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_configuration.colorcategory')),
                ('condition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_configuration.condition')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_configuration.location')),
                ('lock_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_configuration.lockstatus')),
                ('product_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_configuration.productmodelcategory')),
                ('storage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_configuration.storage')),
            ],
        ),
    ]
