# Generated by Django 5.0.7 on 2024-07-31 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_products', '0002_activemobilephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='activemobilephone',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activemobilephone',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
