# Generated by Django 5.0.7 on 2024-08-02 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_products', '0003_activemobilephone_price_and_more'),
        ('product_configuration', '0002_alter_conditioncategory_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRankCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_configuration.category')),
            ],
        ),
    ]
