# Generated by Django 5.0.7 on 2024-08-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_products', '0004_productrankcounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='activemobilephone',
            name='ranking',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
