# Generated by Django 5.0.7 on 2024-08-08 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_products', '0005_activemobilephone_ranking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activemobilephone',
            old_name='price',
            new_name='sold_price',
        ),
    ]
