# Generated by Django 5.0.7 on 2024-08-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_products', '0006_rename_price_activemobilephone_sold_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='activemobilephone',
            name='scraping_url',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='scraping_url',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
