# Generated by Django 5.0.7 on 2024-08-21 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_products', '0007_activemobilephone_scraping_url_and_more'),
        ('product_configuration', '0003_ebaydomain_remove_location_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activemobilephone',
            name='ebay_domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_configuration.ebaydomain'),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='ebay_domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_configuration.ebaydomain'),
        ),
    ]
