# Generated by Django 5.0.7 on 2024-07-18 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_configuration', '0012_remove_productmodelcategory_brand_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_configuration.category')),
            ],
        ),
        migrations.CreateModel(
            name='MobileScrapingProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_model', models.CharField(max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                ('condition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_configuration.condition')),
                ('scraping_process', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scraping_scheduler.scrapingprocess')),
            ],
        ),
    ]
