# Generated by Django 5.0.7 on 2024-07-18 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_configuration', '0012_remove_productmodelcategory_brand_category'),
        ('scraping_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilescrapingprocess',
            name='condition',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product_configuration.condition'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mobilescrapingprocess',
            name='scraping_process',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scraping_scheduler.scrapingprocess'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scrapingprocess',
            name='category',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='product_configuration.category'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='mobilescrapingprocess',
            unique_together={('scraping_process', 'condition')},
        ),
    ]
