# Generated by Django 5.0.7 on 2024-07-18 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping_scheduler', '0002_alter_mobilescrapingprocess_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilescrapingprocess',
            name='mobile_model',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
