# Generated by Django 5.0.7 on 2024-08-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EbayStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ebay_store_id', models.CharField(max_length=100, unique=True)),
                ('url', models.TextField()),
                ('feedback', models.DecimalField(decimal_places=2, max_digits=10)),
                ('items_sold', models.BigIntegerField()),
                ('followers', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
