# Generated by Django 5.0.7 on 2024-08-28 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitor_analysis', '0001_initial'),
        ('product_configuration', '0005_alter_ebaydomain_name_alter_location_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_configuration.category')),
                ('ebay_store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='competitor_analysis.ebaystore')),
            ],
        ),
    ]
