# Generated by Django 5.0.7 on 2024-09-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitor_analysis', '0002_storecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebaystore',
            name='ssn_code',
            field=models.CharField(default='', max_length=50),
        ),
    ]
