# Generated by Django 5.0.7 on 2024-09-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitor_analysis', '0003_ebaystore_ssn_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebaystore',
            name='category_param',
            field=models.CharField(default='store_cat', max_length=50),
        ),
    ]
