# Generated by Django 5.0.7 on 2024-09-16 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitor_analysis', '0004_ebaystore_category_param'),
        ('product_configuration', '0006_alter_category_ebay_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbayStoreProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('shipping_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ebay_item_id', models.BigIntegerField()),
                ('product_url', models.CharField(max_length=255, unique=True)),
                ('image', models.TextField()),
                ('sold_date', models.DateField(null=True)),
                ('is_sold_listing', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_configuration.category')),
                ('ebay_store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='competitor_analysis.ebaystore')),
            ],
        ),
    ]
