# Generated by Django 5.0.7 on 2024-09-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitor_analysis', '0005_ebaystoreproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebaystoreproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
