# Generated by Django 5.0.7 on 2024-09-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitor_analysis', '0006_ebaystoreproduct_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebaystore',
            name='feedback',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ebaystore',
            name='followers',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ebaystore',
            name='items_sold',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ebaystore',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ebaystoreproduct',
            name='ebay_item_id',
            field=models.CharField(max_length=100),
        ),
    ]
