# Generated by Django 5.0.7 on 2024-07-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_configuration', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conditioncategory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='conditioncategory',
            name='is_sold_listing',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='conditioncategory',
            unique_together={('condition', 'category', 'is_sold_listing')},
        ),
    ]
