# Generated by Django 5.0.7 on 2024-08-21 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_configuration', '0002_alter_conditioncategory_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbayDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='location',
            name='domain',
        ),
        migrations.AddField(
            model_name='location',
            name='postal_code',
            field=models.BigIntegerField(default=0),
        ),
    ]
