# Generated by Django 5.0.7 on 2024-08-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_configuration', '0003_ebaydomain_remove_location_domain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='postal_code',
            field=models.CharField(default='', max_length=50),
        ),
    ]
