# Generated by Django 5.0.7 on 2024-08-21 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_configuration', '0004_alter_location_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebaydomain',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(default=None, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
