# Generated by Django 5.0.7 on 2024-09-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_configuration', '0005_alter_ebaydomain_name_alter_location_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='ebay_category_id',
            field=models.BigIntegerField(db_index=True, unique=True),
        ),
    ]
